# Generated by Django 2.2.4 on 2019-08-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=512)),
                ('total_duration', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('thumbnail', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_play', models.DateTimeField(null=True)),
                ('timer_start', models.PositiveIntegerField(default=0)),
                ('service', models.CharField(max_length=255)),
                ('one_shot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MusicQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music')),
            ],
            options={
                'ordering': ('room', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('_shuffle', models.BooleanField(default=False)),
                ('music_queue', models.ManyToManyField(related_name='_room_music_queue_+', through='music.MusicQueue', to='music.Music')),
            ],
        ),
        migrations.AddField(
            model_name='musicqueue',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='music.Room'),
        ),
        migrations.AddField(
            model_name='music',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='music',
            unique_together={('music_id', 'room')},
        ),
    ]
