# Generated by Django 2.2a1 on 2019-01-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='service',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='total_duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.CharField(max_length=512),
        ),
    ]
