# Generated by Django 2.1.5 on 2019-03-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190126_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='listeners',
        ),
    ]
