# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_music_oneshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='oneShot',
            new_name='one_shot',
        ),
    ]
