# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20160323_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ('room', 'track_type', 'order')},
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='track_type',
            field=models.IntegerField(choices=[(0, 'Selected by an user request'), (1, 'Randomly selected')], default=0),
        ),
    ]
