# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_auto_20160712_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='track_type',
            field=models.IntegerField(choices=[(0, '"NORMAL" = Selected by an user request'), (1, '"SHUFFLE" = Randomly selected')], default=0),
        ),
    ]
