version: 2
references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.7
      - image: circleci/redis:5

jobs:
  build:
    working_directory: ~/music
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: dependency-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
  test:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Test
          command: python manage.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
