# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0021_room_listeners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tracks',
            field=models.ManyToManyField(related_name='_room_tracks_+', through='music.PlaylistTrack', to='music.Music'),
        ),
    ]
