# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_auto_20160107_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='nb_shuffle_items',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
